=== PabloCB98/PERFUMES/data/perfumes.dtd
<!--en la etiqueta raíz (catalogo_perfumes), le decimos que dentro
de mi catálgo debe haber una o más etiquetas "temporada" obligatoriamente, 
con el signo más lo hacemos-->
<!ELEMENT catalogo_perfumes (temporada+)>

<!--lo mismo aquí, dentro de temporada debe haber obligatoriamente una o más etiquetas
""momento_dia-->
<!ELEMENT temporada (momento_dia+)>
<!--ATTLIST define los atributos que tiene una etiqueta, en este caso debe ser de invierno o verano, una de las dos opciones-->
<!ATTLIST temporada
    tipo (Invierno | Verano) #REQUIRED>

<!--dentro de momento_dia debe haber uno o más perfumes obligatoriamente, y los atributos
de esta etiqueta deben ser dia o noche -->
<!ELEMENT momento_dia (perfume+)>
<!ATTLIST momento_dia
    tipo (Dia | Noche) #REQUIRED>

<!--definimos la etiqueta perfume, en la que debe contener en su interior los elementos
entre paréntesis y en el orden que se ve-->
<!ELEMENT perfume (nombre, marca, tipo, familia_olfativa, genero, notas, precio, imagen, descripcion,opinion_personal,mi_nota)>
<!--el ID de cada perfume. parte de ser único es obligatorio ponerlo-->
<!ATTLIST perfume
    id ID #REQUIRED>

<!--#PCDATA nos dice que dentro de esos elementos va texto normal-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT familia_olfativa (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT opinion_personal (#PCDATA)>
<!ELEMENT mi_nota (#PCDATA)>


<!--Como las notas se pueden dividir en 3 distintas, directamente indico que dentro de esta
etiquet van las etiquetas salida,corazón y fondo, las cuales llevan dentro texto nromal-->
<!ELEMENT notas (salida, corazon, fondo)>
<!ELEMENT salida (#PCDATA)>
<!ELEMENT corazon (#PCDATA)>
<!ELEMENT fondo (#PCDATA)>

<!--la etiqueta precio contiene un número pero en texto-->
<!ELEMENT precio (#PCDATA)>
<!-- precio acepta cualquier cadena de texto, pero podemos usar símbolos debtro sin que nos de error el XML-->
<!ATTLIST precio
    moneda CDATA #REQUIRED>

<!ELEMENT imagen (#PCDATA)>

<!ELEMENT descripcion (#PCDATA)>

=== PabloCB98/PERFUMES/data/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo_perfumes SYSTEM "perfumes.dtd">

<!-- USO DE LA IA -->
<!-- La he usado para que me diese una descripción de cada perfume de una forma adecuada y breve, también le he
pedido ayuda para que me diese las notas y familias olfativas, ya que yo tengo los perfumes, pero no me sé las notas ni los precios actualizados-->
<!-- Bastante info sacada de la web de Fragántica-->
<!-- Debería estar todo con un léxico correcto y sin faltas ortográficas, ya que he pasado las descripciones por IA para que las tildes sean cambiadas por sus entidades y evitar errores,
unque el xml esté en UTF-8 y no debería dar errores, aún más en los navegadores principales que usaremos. Las opiniones personales las he dejado tal cual las he escrito, como he dicho,
con el UTF-8 no debería dar fallo -->

<catalogo_perfumes>

    <!-- Tengo varias etiquets anidadas, dentro del catálogo, tengo la etiqueta de temporada, verano/invierno, y dentro de la de temporada la de momento del día, día/noche, 
    todo explicado en el dtd-->

    <temporada tipo="Invierno">

        <momento_dia tipo="Dia">

            <!-- He decidido que el id de cada perfume será perfume- número. No van seguidos porque he cambiado alguno a otra temporada o momento del día, según mis gustos
            Todo está bastante claro, es una repetición todo el rato de lo mismo, cambiando los valores de las etiquetas-->

            <perfume id="perfume-001">
                <nombre>Hayaati</nombre>
                <marca>Lattafa</marca>
                <tipo>Eau de Parfum</tipo>
                <familia_olfativa>Aromático Amaderado</familia_olfativa>
                <genero>Unisex</genero>
                <notas>
                    <salida>Manzana, Bergamota</salida>
                    <corazon>Canela, Notas Amaderadas</corazon>
                    <fondo>Almizcle, Vainilla</fondo>
                </notas>
                <precio moneda="EUR">20.00</precio>
                <imagen>imagenes/invierno/dia/hayaati.png</imagen>
                <descripcion>
                    Una fragancia frutal-especiada que combina la frescura de la manzana con la calidez de la canela y un 
                    fondo almizcleado de vainilla. Su perfil dulce y accesible lo convierte en una opci&#243;n perfecta para el d&#237;a de invierno, 
                    c&#243;moda y envolvente sin ser excesiva.
                </descripcion>
                <opinion_personal>La usé mucho en su momento, el primer perfume árabe que me compré. Huele muy bien pero siento que no proyecta mucho ni dura lo suficiente</opinion_personal>
                <mi_nota>6/10</mi_nota>
            </perfume>

            <perfume id="perfume-003">
                <nombre>Tender Amber</nombre>
                <marca>Zara</marca>
                <tipo>Eau de Parfum</tipo>
                <familia_olfativa>Oriental Floral</familia_olfativa>
                <genero>Masculino</genero>
                <notas>
                    <salida>Frutas Exóticas, Grosella Negra</salida>
                    <corazon>Rosa, Tuberosa</corazon>
                    <fondo>Ámbar</fondo>
                </notas>
                <precio moneda="EUR">18.00</precio>
                <imagen>imagenes/invierno/dia/tender.png</imagen>
                <descripcion>
                    Una fragancia sorprendentemente rica para su precio, con una apertura frutal y jugosa que evoluciona 
                    hacia un coraz&#243;n floral de rosa y tuberosa sobre un fondo c&#225;lido de &#225;mbar. Perfecta para d&#237;as de invierno, 
                    deja una estela dulce y acogedora que recuerda a Erba Pura de Xerjoff.                
                </descripcion>
                <opinion_personal>
                    Muy buen perfume a un precio súper barato. Tiene su parecido a Erba Pura. En ropa dura lo suficiente y huele bien, la uso actualmente para 
                    ir al gimnasio, al pádel o si voy a salir de cada poco rato. Personalmente no la pondria en invierno, sinó en verano/día
                </opinion_personal>
                <mi_nota>5.5/10</mi_nota>
            </perfume>

        </momento_dia>

        <momento_dia tipo="Noche">

            <perfume id="perfume-004">
                <nombre>Liquid Brun</nombre>
                <marca>French Avenue</marca>
                <tipo>Eau de Parfum</tipo>
                <familia_olfativa>Amaderado Gourmand</familia_olfativa>
                <genero>Unisex</genero>
                <notas>
                    <salida>Canela, Flor de Naranjo, Cardamomo, Bergamota</salida>
                    <corazon>Vainilla Bourbon, Elemi</corazon>
                    <fondo>Praliné, Ambroxan, Palo de Guayaco, Almizcle</fondo>
                </notas>
                <precio moneda="EUR">30.00</precio>
                <imagen>imagenes/invierno/noche/liquid.jpeg</imagen>
                <descripcion>
                    Un gourmand amaderado lanzado en 2024 que combina especias c&#225;lidas con vainilla cremosa y un fondo rico de pralin&#233; 
                    y ambroxan. Considerado dupe del PDM Altha&#239;r, seduce con una estela dulce, especiada y moderna. Ideal para noches de invierno, 
                    con una proyecci&#243;n de hasta 12 horas.
                </descripcion>
                <opinion_personal>La mejor árabe que me he comprado, dura muchísimo y el olor es de lo mejorcito que tengo, un dupe de un perfume muy conocido. Nada mñas que decir, es TOP</opinion_personal>
                <mi_nota>9/10</mi_nota>
            </perfume>

            <perfume id="perfume-005">
                <nombre>Rifaaqat</nombre>
                <marca>Paris Corner</marca>
                <tipo>Eau de Parfum</tipo>
                <familia_olfativa>Oriental Especiado</familia_olfativa>
                <genero>Unisex</genero>
                <notas>
                    <salida>Pimienta Negra, Elemi, Pimienta Rosa</salida>
                    <corazon>Olibano, Azafrán</corazon>
                    <fondo>Vainilla, Cedro</fondo>
                </notas>
                <precio moneda="EUR">25.00</precio>
                <imagen>imagenes/invierno/noche/rifaaqat.jpeg</imagen>

                <descripcion>
                    Una fragancia especiada y misteriosa inspirada en YSL Babycat, con una apertura picante de pimientas y elemi que 
                    da paso a azafr&#225;n y olibano. El fondo de vainilla y cedro aporta una calidez adictiva. Perfecta para noches fr&#237;as de invierno, 
                    con una proyecci&#243;n resinosa y memorable.
                </descripcion>
                <opinion_personal>La quería probar y me la regalaron, huele bien pero no es para todos los gustos, muy empalagosa. Personalmente a mi me gusta aunque no la use apenas. Dura mucho, como todas las árabes</opinion_personal>
                <mi_nota>6.5/10</mi_nota>

            </perfume>

            <perfume id="perfume-006">
                <nombre>Momento</nombre>
                <marca>Riiffs</marca>
                <tipo>Extrait de Parfum</tipo>
                <familia_olfativa>Amaderado Especiado</familia_olfativa>
                <genero>Unisex/Masculino</genero>
                <notas>
                    <salida>Azúcar, Azafrán, Mandarina</salida>
                    <corazon>Tonka, Rosa de Damasco, Oud</corazon>
                    <fondo>Amberwood, Caramelo, Cedro</fondo>
                </notas>
                <precio moneda="EUR">28.00</precio>
                <imagen>imagenes/invierno/noche/momento.jpg</imagen>

                <descripcion>
                    Un extrait de parfum lujoso que abre con mandarina y azafr&#225;n sobre un coraz&#243;n de rosa y oud, evolucionando hacia un fondo de caramelo, 
                    amberwood y cedro. Estela c&#225;lida y sofisticada, considerada por muchos una alternativa de calidad al Montale Arabians Tonka. Perfecta 
                    para noches de invierno.
                </descripcion>
                <opinion_personal>Muy buena compra y MUY barata. Huele y dura mucho, sin llegar a empalagar, algo raro en perfumes árabes, recomendado al 100%</opinion_personal>
                <mi_nota>6.75/10</mi_nota>

            </perfume>


            <perfume id="perfume-008">
                <nombre>Club de Nuit Untold</nombre>
                <marca>Armaf</marca>
                <tipo>Eau de Parfum</tipo>
                <familia_olfativa>Oriental Ambarino</familia_olfativa>
                <genero>Unisex</genero>
                <notas>
                    <salida>Azafrán, Jazmín</salida>
                    <corazon>Amberwood, Ambra Gris</corazon>
                    <fondo>Resina de Abeto, Cedro</fondo>
                </notas>
                <precio moneda="EUR">35.00</precio>
                <imagen>imagenes/invierno/noche/untold.jpeg</imagen>

                <descripcion>
                    Lanzado en 2022, es un dupe orientado al ADN del Baccarat Rouge 540, con una nube dulce y ambarina de amberwood y ambra gris sobre un fondo resinoso 
                    de cedro. Su proyecci&#243;n es bestia en las primeras horas, convirti&#233;ndose en un sillage de piel suave y duradero. Noche de invierno por excelencia.
                </descripcion>
                <opinion_personal>Es el perfume perfecto para invierno, tanto de día como de noche, incluso en noches de verano lo usaría sin abusar de él, de lo mejorcito</opinion_personal>
                <mi_nota>7.75/10</mi_nota>

            </perfume>

            <perfume id="perfume-009">
                <nombre>212 VIP Black</nombre>
                <marca>Carolina Herrera</marca>
                <tipo>Eau de Parfum</tipo>
                <familia_olfativa>Aromático Fougère</familia_olfativa>
                <genero>Masculino</genero>
                <notas>
                    <salida>Absenta, Anís, Hinojo</salida>
